### ISSUE TITLE
Vector laws

### ISSUE THREAD

**Issue by Bodigrim** [andrewthad/quickcheck-classes#88]
It would be nice to have a list of `Vector` / `MVector` laws, similar in spirit to `Primitive` ones. If it sounds reasonable for you, I can prepare a PR.

The reason for this is that I've been recently fixing an incorrect `MVector.basicInitialize` instance in https://github.com/mokus0/bitvec/pull/6 and would like to test whether other methods are correct.

**Comment by chessai** [comment]
yes, this would be great. just make sure to respect any relevant CPP. This package must build with GHC >= 7.4.2, and we'd need a compilation flag that would disable building the vector laws.

**Comment by andrewthad** [comment]
Testing the vector laws would be great. Before preparing a PR, could you write out what you expect the type signature of the laws property test to be (using fully qualified names since `Vector` means several different things in the `vector` package)? Since the typeclasses in `Vector` are MPTC and data family heavily, I'm not totally sure what I expect the type signature to look like.

**Comment by chessai** [comment]
yeah, also you might run into the quantifiedconstraints + type families problem, so this might be similar to `generic1Laws` where you're just stuck with Eq1/Show1 etc.

**Comment by Bodigrim** [comment]
To keep things simple, I think it is enough to test unboxed vectors only. I've never seen other instances of `Data.Vector.Generic` in the wild and I expect that the key instance `Data.Vector` is kinda well-tested. So properties can be like this:

```haskell
muvectorWriteRead :: forall a. (Eq a, MU.Unbox a, Arbitrary a, Show a) => Proxy a -> Property
```

I've prepared a prototype in #89.

**Comment by andrewthad** [comment]
Testing unboxed vectors only seems fine. That certainly simplifies the constraints. Your prototype looks like it's going in the right direction.
