### ISSUE TITLE
consolidate with hedgehog-classes

### ISSUE THREAD

**Issue by chessai** [andrewthad/quickcheck-classes#92]
Both hedgehog-classes and quickcheck-classes use essentially the same techniques and internals. I think that the Common stuff (Common.hs in quickcheck-classes, Common.* in hedgehog-classes) should be abstracted into a single library that builds with GHC >= 7.4 (barring generators/arbitrary instances, to avoid depending on either QuickCheck or Hedgehog). The most important part of this is the Laws datatype. My current vision for these two libraries is for them to sit side by side, mirroring each other, using the two different backends.

**Comment by andrewthad** [comment]
There's a decent amount of code in `Common.hs` that is specific to `QuickCheck`, stuff mentioning `Arbitrary` and `Property`. And the stuff in there mostly lacks cohesion. It's just a bunch of random functions and datatypes that got stuck there because multiple modules in `quickcheck-classes` used it. I think a more fruitful goal would be to somehow write backend-agnostic `monoidLaws`, `ordLaws`, etc. such that either test suite can be plugged in. I don't know what these would look like though. You would have to abstract over the concept of generating and shrinking in such a way that either library could be plugged in. And you'd have to abstract over displaying counterexamples. I suspect that this is possible, but it's not immediately obvious how to go about this.

**Comment by andrewthad** [comment]
> this is at least a step in that direction

This is what I have a hard time getting behind (although I like the idea of a backend-agnostic core). Factoring out the stuff from `Common` and `Common.*` would lead to a library with a confusing motivation. The motivation would be something like "all the little helper functions and data types that `hedgehog-classes` and `quickcheck-classes` need". Here are the difficulties I see:

* There is a maintenance burden associated with this since some changes now require two releases. And what to do when there a something from the common library is no longer needed? Remove it?
* How can people contribute to this common library? The guidelines would need to be something along the lines of "this library exists for the purpose of housing types and functions needed in two other specific projects". But this seems very much like a `MissingH`-style library: a grab bag of combinators that lack cohesive purpose.

The backend-agnostic core, by contrast, would have a more clear motivation. Someone could add laws tests to it with no knowledge of of its downstream dependencies.

**Comment by chessai** [comment]
Ok makes sense
