### ISSUE TITLE
missing eq laws

### ISSUE THREAD

**Issue by chessai** [andrewthad/quickcheck-classes#94]
Substitutivity
if x == y = True and f is a "public" function whose return type is an instance of Eq, then f x == f y = True
Negation
x /= y = not (x == y)

**Comment by chessai** [comment]
we cannot test substitutivity, because any function we could provide would have to discard its argument. we could do some unsafe things with ptr equality but this sounds dangerous and unreliable!

we can definitely test negation though.

**Comment by andrewthad** [comment]
Yeah, negation's a good one to do, and substitutivity is impossible.

**Comment by bagrounds** [comment]
> we cannot test substitutivity, because any function we could provide would have to discard its argument.

Can you explain this?

Why would the function have to discard its argument?

**Comment by chessai** [comment]
@bagrounds

Definition of substitutivity (just making sure we're on the same page):

```
x, y :: Eq a => a
f :: Eq b => a -> b

if x == y then f x == f y == True
```

Basically, if `x` and `y` are equal, then `f x` should equal `f y`.

Now, let's look at how a test for this would look:

```
subst :: forall a. (Eq a, Arbitrary a) => Proxy a -> Property
subst _ = property $ \(x :: a) (y :: a) -> (x == y) ==> (f x == f y) -- in practise we wouldn't use implication, but it signals the intention
``` 

What should `f` be? Recall that `f` has type `f :: (Eq a, Eq b) => a -> b` (where `a` unifies with `subst`'s `a`). We can of course pick `b` to be anything we want with a lawful `Eq` instance - the problem is `a`. Assume `b ~ [Integer]`. How do you write the function `f :: Eq a => a -> [Integer]` that uses its argument in any meaningful way? You can't. Eq doesn't admit enough structure.

**Comment by bagrounds** [comment]
@chessai - thanks for that very clear explanation!

Is there any reason not to ask for an arbitrary function in order to test substitutivity?

Perhaps something like this:
```
eqSubstitutive :: forall a b.
  (Show a, Eq a, Arbitrary a, CoArbitrary a, Function a, Show b, Eq b, Arbitrary b)
  => Proxy a -> Proxy b -> Property
eqSubstitutive _ _ = property $ \(a :: a) (b :: a) (f :: Fun a b) ->
  a == b ==> applyFun f a == applyFun f b

```

**Comment by chessai** [comment]
@bagrounds

The main problem is API uniformity: This would require us to branch off with new API 'endpoints', so to speak. if everything just has type `Proxy x -> Laws`, things are really easy (one of the main points of quickcheck-classes).

I have another hunch about the generators for Fun performing poorly. I'm not sure on that though.

**Comment by chessai** [comment]
By 'performing', i mean w.r.t. discarding/shrinking.

**Comment by bagrounds** [comment]
> The main problem is API uniformity: This would require us to branch off with new API 'endpoints', so to speak. if everything just has type `Proxy x -> Laws`, things are really easy (one of the main points of quickcheck-classes).

This is an important point.
Before picking up quickcheck-classes, I tried 2 or 3 alternative libraries, but they were just difficult enough to get working that I gave up and moved on. Getting quickcheck-classes working was a snap.

If we want to maintain the `Proxy x -> Laws` API, perhaps we can compromise a bit and pick our arbitrary `b` up front. For example:

```hs
eqSubstitutive :: forall a.
  (Show a, Eq a, Arbitrary a, CoArbitrary a, Function a) => Proxy a -> Property
eqSubstitutive _ = property $ \(a :: a) (b :: a) (f :: Fun a Integer) ->
  a == b ==> applyFun f a == applyFun f b
```

In fact, I'm not sure that this adjustment sacrifices any real value. Since generating arbitrary values of type `b` relies on a mapping from random numbers, perhaps we don't lose any generality by just using random numbers directly.

However, just because we can implement this law, doesn't necessarily imply that we should. Is it even necessary to test this law? I'm not really sure, but I did find an interesting example.

```hs
{-# LANGUAGE DeriveGeneric, DerivingVia, StandaloneDeriving #-}
newtype BadEq = BadEq Int deriving (Show, Arbitrary, CoArbitrary) via Int
instance Eq BadEq where (BadEq a) == (BadEq b) = abs a == abs b
deriving instance Generic BadEq
instance Function BadEq
```

Testing this definition of `BadEq` locally, I find that it always passes the Transitive, Symmetric, and Reflexive laws - but it quickly fails the substitutive law as defined above.

Thoughts?

**Comment by chessai** [comment]
it's possible we could add that as a separate top-level test. perhaps this wouldn't be too out of the ordinary given the several semigroup tests, (though they all have the same type signature, so it is a bit different). my other concern was over whether or not `Fun` wouldn't just discard a ton. using implication is dangerous because of this, and i'm not sure how quickcheck constrains function domain/codomain. 

additionally, the pattern `instance Eq X where a == b = f a == f b` is kind of dubious, and i doubt it's used in practise where it isn't questioned by writers/readers.

overall i'm not convinced that it should be added, but not totally opposed.

**Comment by andrewthad** [comment]
> If we want to maintain the `Proxy x -> Laws` API, perhaps we can compromise a bit and pick our arbitrary `b` up front.

That's fine. In fact, all of the tests for things of kind `Type -> Type` and `Type -> Type -> Type` already do this. So I consider that consistent with the existing API. This only concern I have  I'm most concerned with is how difficult it is for people to write out `Function` and `Coarbitrary` instances for their data types. I think it's best to leave `eqLaws` alone since adding constraint would break existing uses and make it harder to use, but I like the implementation of `eqSubstitutive`. The function I would want exposed to end users would be:

    substitutiveEqLaws :: (Eq a, Arbitrary a, Coarbitrary a, Function a, Show a) => Proxy a -> Laws

The haddocks for `eqLaws` should reference this additional function so that users who want every check possibly get it (at the cost of writing additional instances), and the haddocks for `substitutiveEqLaws` should make it clear that it only checks substitutivity and should always be combined with `eqLaws`.
