### ISSUE TITLE
Data.Semigroup.Sum isn't good for testing

### ISSUE THREAD

**Issue by sjakobi** [andrewthad/quickcheck-classes#98]
https://github.com/andrewthad/quickcheck-classes/pull/97 demonstrates how an illegal Foldable instance goes undetected.

IMHO the problem is that `quickcheck-classes` internally uses `Sum` which is a commutative semigroup. That means it can't detect when things are `<>`'d in the wrong order.

I suspect that a free semigroup like `[]` or `Sequence` would be a better fit. If performance is an issue with these, perhaps `First` could be enough!?

**Comment by chessai** [comment]
Ah, good catch. We should certainly use a non-commutative semigroup here.

**Comment by andrewthad** [comment]
Agreed, sum is a poor choice here. List is a good option since it’s the free Monoid, preserving as much information as possible. I’m wary of First since it discards so much information. I think that if we use list internally  as the semigroup, we’ll want to be careful to use a custom generator instead of the one provided by the Arbitrary instance. It’s better to pick small lists for this (between zero and two elements in length). Larger ones can make tests run noticeably slower since the test would end up concatenating a bunch of them.

**Comment by chessai** [comment]
> Agreed, sum is a poor choice here. List is a good option since it’s the free Monoid, preserving as much information as possible. I’m wary of First since it discards so much information. I think that if we use list internally as the semigroup, we’ll want to be careful to use a custom generator instead of the one provided by the Arbitrary instance. It’s better to pick small lists for this (between zero and two elements in length). Larger ones can make tests run noticeably slower since the test would end up concatenating a bunch of them.

Yeah, I agree that we should use list.

**Comment by sjakobi** [comment]
Thanks for the fix @chessai!

Note that there are more dubious uses of `Sum`, e.g. for `Bifoldable`.

**Comment by chessai** [comment]
keeping this open until all are resolved
